### ISSUE TITLE
https://www.v2know.com/rss/ encoding issue

### ISSUE THREAD

**Issue by guyskk** [EKsumic/December-2020-Sagittarius-Guild-Battle#1]
Hi @EKsumic, I didn't find your email, so report here. 

The encoding in RSS feed `<?xml version="1.0" encoding="utf-16"?>` is not correct, the actual content encoding is `utf-8`.

**Comment by EKsumic** [comment]
I clicked on it https://www.v2know.com/rss/ Then Ctrl+F searched for utf-16, but no results were found, so I don't know what you're talking about. And I'm sorry for replying so late because I only discovered this message now.

> Hi @EKsumic, I didn't find your email, so report here.
> 
> The encoding in RSS feed `<?xml version="1.0" encoding="utf-16"?>` is not correct, the actual content encoding is `utf-8`.

**Comment by EKsumic** [comment]
> Hi @EKsumic, I didn't find your email, so report here.
> 
> The encoding in RSS feed `<?xml version="1.0" encoding="utf-16"?>` is not correct, the actual content encoding is `utf-8`.

Hi @guyskk,

I have fixed the issue. You can check it now. 

Additionally, thank you for informing me.

Best regards,

EKsumic
